---
http_interactions:
- request:
    method: post
    uri: https://cognito-idp.us-east-1.amazonaws.com/
    body:
      encoding: UTF-8
      string: '{"ClientId":"76jcq337aei27va9q9gtaep0dh","Username":"john.doe@doe.com","Password":"changeME123!","UserAttributes":[{"Name":"email","Value":"john.doe@doe.com"}]}'
    headers:
      Content-Type:
      - application/x-amz-json-1.1
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.38.0 ruby/2.5.3 x86_64-darwin18 aws-sdk-cognitoidentityprovider/1.10.0
      X-Amz-Target:
      - AWSCognitoIdentityProviderService.SignUp
      Content-Length:
      - '160'
      Accept:
      - "*/*"
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Date:
      - Thu, 15 Nov 2018 04:35:46 GMT
      Content-Type:
      - application/x-amz-json-1.1
      Content-Length:
      - '68'
      Connection:
      - keep-alive
      X-Amzn-Requestid:
      - eb757195-e88f-11e8-a2e2-93cc7bc5791a
      X-Amzn-Errortype:
      - 'UsernameExistsException:'
      X-Amzn-Errormessage:
      - User already exists
    body:
      encoding: UTF-8
      string: '{"__type":"UsernameExistsException","message":"User already exists"}'
    http_version: 
  recorded_at: Thu, 15 Nov 2018 04:35:46 GMT
recorded_with: VCR 4.0.0
